import type { Product } from "./types"

export const products: Product[] = [
  {
    id: "1",
    name: "Classic T-Shirt",
    description: "A comfortable and stylish t-shirt for everyday wear.",
    price: 29.99,
    image: "/placeholder.svg?height=400&width=300",
    category: "men",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "White", "Gray"],
  },
  {
    id: "2",
    name: "Slim Fit Jeans",
    description: "Modern slim fit jeans with a comfortable stretch.",
    price: 59.99,
    image: "/placeholder.svg?height=400&width=300",
    category: "men",
    sizes: ["30", "32", "34", "36"],
    colors: ["Blue", "Black", "Gray"],
  },
  {
    id: "3",
    name: "Casual Hoodie",
    description: "A warm and cozy hoodie perfect for casual outings.",
    price: 49.99,
    image: "/placeholder.svg?height=400&width=300",
    category: "men",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Gray", "Navy"],
  },
  {
    id: "4",
    name: "Summer Shorts",
    description: "Lightweight shorts ideal for summer days.",
    price: 34.99,
    image: "/placeholder.svg?height=400&width=300",
    category: "men",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Beige", "Blue", "Green"],
  },
  {
    id: "5",
    name: "Floral Dress",
    description: "A beautiful floral dress for special occasions.",
    price: 79.99,
    image: "/placeholder.svg?height=400&width=300",
    category: "women",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Red", "Blue", "Yellow"],
  },
  {
    id: "6",
    name: "Casual Blouse",
    description: "A lightweight blouse perfect for work or casual wear.",
    price: 39.99,
    image: "/placeholder.svg?height=400&width=300",
    category: "women",
    sizes: ["XS", "S", "M", "L"],
    colors: ["White", "Pink", "Blue"],
  },
  {
    id: "7",
    name: "Skinny Jeans",
    description: "Flattering skinny jeans with a high waist.",
    price: 54.99,
    image: "/placeholder.svg?height=400&width=300",
    category: "women",
    sizes: ["26", "28", "30", "32"],
    colors: ["Blue", "Black", "Gray"],
  },
  {
    id: "8",
    name: "Summer Skirt",
    description: "A light and flowy skirt for summer days.",
    price: 44.99,
    image: "/placeholder.svg?height=400&width=300",
    category: "women",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Yellow", "Green", "Blue"],
  },
  {
    id: "9",
    name: "Kids T-Shirt",
    description: "A fun and colorful t-shirt for kids.",
    price: 19.99,
    image: "/placeholder.svg?height=400&width=300",
    category: "kids",
    sizes: ["3-4Y", "5-6Y", "7-8Y", "9-10Y"],
    colors: ["Red", "Blue", "Green"],
  },
  {
    id: "10",
    name: "Kids Jeans",
    description: "Durable and comfortable jeans for active kids.",
    price: 29.99,
    image: "/placeholder.svg?height=400&width=300",
    category: "kids",
    sizes: ["3-4Y", "5-6Y", "7-8Y", "9-10Y"],
    colors: ["Blue", "Black"],
  },
  {
    id: "11",
    name: "Kids Hoodie",
    description: "A warm hoodie with fun designs for kids.",
    price: 34.99,
    image: "/placeholder.svg?height=400&width=300",
    category: "kids",
    sizes: ["3-4Y", "5-6Y", "7-8Y", "9-10Y"],
    colors: ["Red", "Blue", "Green"],
  },
  {
    id: "12",
    name: "Kids Shorts",
    description: "Comfortable shorts for active kids.",
    price: 24.99,
    image: "/placeholder.svg?height=400&width=300",
    category: "kids",
    sizes: ["3-4Y", "5-6Y", "7-8Y", "9-10Y"],
    colors: ["Blue", "Green", "Red"],
  },
  {
    id: "13",
    name: "Baseball Cap",
    description: "A stylish baseball cap for casual wear.",
    price: 24.99,
    image: "/placeholder.svg?height=400&width=300",
    category: "men",
    sizes: ["One Size"],
    colors: ["Black", "Navy", "Red"],
  },
  {
    id: "14",
    name: "Leather Belt",
    description: "A high-quality leather belt for any occasion.",
    price: 39.99,
    image: "/placeholder.svg?height=400&width=300",
    category: "men",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Brown"],
  },
  {
    id: "15",
    name: "Wool Scarf",
    description: "A warm wool scarf for cold days.",
    price: 29.99,
    image: "/placeholder.svg?height=400&width=300",
    category: "women",
    sizes: ["One Size"],
    colors: ["Red", "Gray", "Black"],
  },
]
